kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.app.image }}
          imagePullPolicy: {{ .Values.imageConfig.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-envs
          ports:
              - containerPort: {{ .Values.service.targetPort }}
                protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sleep", "5"]
