apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-envs
data:
  {{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

  {{ range (split "\n" ((tpl .Values.envFile .) | trimSuffix "\n" ))}}
  {{- $a := (splitn "=" 2 .) -}}
  {{- if $a._0 -}}
  {{ $a._0 | indent 2}}: {{ $a._1 | quote }}
  {{ end -}}
  {{ end}}

